# Generated by Django 4.2.11 on 2024-04-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_customer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='number',
        ),
    ]
