# Generated by Django 4.2.11 on 2024-04-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_employees_delete_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
